name: vez
description: "A social media to create and enjoy real life events."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  crypto: ^3.0.7
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # aggiungi la versione qui

# icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  # "standard" icon for iOS and old Android versions
  image_path: "assets/app_icon/app_icon.png"

  # adaptive icons
  adaptive_icon_background: "assets/app_icon/app_icon_background.png" # back bg
  adaptive_icon_foreground: "assets/app_icon/app_icon_foreground.png" # the image in the logo

flutter:
  uses-material-design: true

  # RICORDATI DI AGGIUNGERE GLI ASSETS QUI PER L'ICONA E LE FOTO
  assets:
    - assets/app_icon/app_icon.png

  fonts:
    - family: InstagramSans
      fonts:
        - asset: assets/fonts/InstagramSans-Bold.ttf
        - asset: assets/fonts/InstagramSans-Regular.ttf
          style: normal